# Generated by Django 6.0.6 on 2026-10-05 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APKScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('package', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('certificate', models.CharField(blank=True, default='', max_length=50)),
                ('risk_score', models.IntegerField(default=0)),
                ('classification', models.CharField(default='Pending', max_length=20)),
                ('malware_family', models.CharField(blank=True, max_length=100, null=True)),
                ('malware_category', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_confidence', models.IntegerField(default=0)),
                ('family_match', models.IntegerField(default=0)),
                ('detected_risks', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True, default='')),
                ('recommendation', models.TextField(blank=True, default='')),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scan_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
