# Generated by Django 6.1.1 on 2026-10-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_malwarefamily_apkscan_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkscan',
            name='capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
